POWERLEVEL9K_SHORTEN_DIR_LENGTH=1  
POWERLEVEL9K_SHORTEN_DELIMITER=""  
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"  
POWERLEVEL9K_PROMPT_ON_NEWLINE=true  
#espacios entre inconos a la izquierda  
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""  
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""  
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=" "  
#espacios entre iconos a la derecha  
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""  
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=" "  
POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS="" #espacios a la derecha icono 
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}" 
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} " 
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon disk_usage ram root_indicator dir dir_writable_joined)  
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs time_joined node_version)  
#color de configuracion de git  
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"  
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"  
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"  
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"  
#os icon background  
POWERLEVEL9K_OS_ICON_BACKGROUND="clear"  
POWERLEVEL9K_OS_ICON_FOREGROUND="015"  
#dir  
POWERLEVEL9K_SHORTEN_DELIMITER=".."  
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2  
#Disk usage  
POWERLEVEL9K_DISK_USAGE_NORMAL_BACKGROUND="clear"  
POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND="121"  
POWERLEVEL9K_DISK_USAGE_WARNING_BACKGROUND="clear"  
POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND="202"  
POWERLEVEL9K_DISK_USAGE_CRITICAL_BACKGROUND="clear"  
POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND="196"  
#RAM colors  
POWERLEVEL9K_RAM_BACKGROUND="clear"  
POWERLEVEL9K_RAM_FOREGROUND="yellow"  
#node version color  
POWERLEVEL9K_NODE_VERSION_BACKGROUND="clear"  
POWERLEVEL9K_NODE_VERSION_FOREGROUND="green"  
#home and dir colors  
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"  
POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"  
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"  
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"  
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"  
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"  
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"  
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"  
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"  
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white" 
#status color  
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"  
POWERLEVEL9K_STATUS_OK_FOREGROUND="blue"  
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"  
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"  
#time color  
POWERLEVEL9K_TIME_BACKGROUND="clear"  
POWERLEVEL9K_TIME_FOREGROUND="whitte"  
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="clear"  
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="magenta"  
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="clear"  
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="green"  
# RIGHT_PROMPT Github  
# =========================================================== 
# vcs branch of git conffiguration  
#POWERLEVEL9K_SHOW_CHANGESET=true  
#POWERLEVEL9K_CHANGESET_HASH_LENGTH=6  
#showing efects of change status git  
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="none"  
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="076"  
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="none"  
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="005"  
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="none"  
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="003"  
#showing efects of github  
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname) 
